export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const CUSTOMER_REPOSITORY = Symbol('CUSTOMER_REPOSITORY');
export const ITEM_REPOSITORY = Symbol('ITEM_REPOSITORY');
export const STOCK_REPOSITORY = Symbol('STOCK_REPOSITORY');
export const TRANSACTION_REPOSITORY = Symbol('TRANSACTION_REPOSITORY');
export const TRANSACTION_ITEM_REPOSITORY = Symbol(
  'TRANSACTION_ITEM_REPOSITORY',
);
export const DEBT_REPOSITORY = Symbol('DEBT_REPOSITORY');
export const SUPPLIER_REPOSITORY = Symbol('SUPPLIER_REPOSITORY');
export const SUPPLIER_DEBT_REPOSITORY = Symbol('SUPPLIER_DEBT_REPOSITORY');
export const STAFF_REPOSITORY = Symbol('STAFF_REPOSITORY');
export const REPORT_REPOSITORY = Symbol('REPORT_REPOSITORY');
export const REFUND_REPOSITORY = Symbol('REFUND_REPOSITORY');
export const EXCHANGE_ITEM_REPOSITORY = Symbol('EXCHANGE_ITEM_REPOSITORY');
export const PAYMENT_ACCOUNT_REPOSITORY = Symbol('PAYMENT_ACCOUNT_REPOSITORY');
